/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package izinVermeIslemleri;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import veritabani.VeritabaniBaglantisi;

public class YeniIzinVerme extends javax.swing.JFrame {

    /**
     * Creates new form YeniIzinVerme
     */
    public YeniIzinVerme() {
        initComponents();
        kayitNoOtomatikAl();
        sicilNoComboboxDuzenle();
    }

    VeritabaniBaglantisi vb = new VeritabaniBaglantisi();
    public Statement baglantiAc() throws SQLException {
        
        try {
            Class.forName(vb.DRIVER).newInstance();
            vb.con = DriverManager.getConnection(vb.URL + vb.DB_NAME, vb.ID, vb.PW);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Veritabanı Bağlantı Hatası!!!\n" + e);
        }
        return vb.con.createStatement();
    }
    
    public void baglantiKapat() throws SQLException {
        vb.con.close();
    }
    
    private void kayitNoOtomatikAl() {
        
        try {
            
            Statement s = baglantiAc();
            String sql = "SELECT kayit_no FROM izinler ORDER BY kayit_no DESC LIMIT 1";
            
            ResultSet rs = s.executeQuery(sql);
            
            String kayitNo = "";
            while(rs.next()) {
                kayitNo = rs.getString("kayit_no");
            }
            baglantiKapat();
            
            kayitNoLbl.setText(Integer.toString(Integer.parseInt(kayitNo) + 1));
            
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Kayıt No Bulunurken Hata Meydana Geldi!\n" + e);
        }
    }
    
    private void sicilNoComboboxDuzenle() {
        
        try {
            
            Statement s = baglantiAc();
            String sql = "SELECT sicil_no FROM kisi_bilgi";
            
            ResultSet rs = s.executeQuery(sql);
            
            while(rs.next()) {
                sicilNoCbx.addItem(rs.getObject("sicil_no"));
            }
            baglantiKapat();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sicil No bulmak için "
                    + "veritabanına bağlanırken bir hata meydana geldi!\n" + e);
        }
    }
    
    private void yeniIzinVer() {
        
        try {
            
            YeniIzinEkle izin = new YeniIzinEkle(birimTf.getText(), kayitNoLbl.getText(),
                    sicilNoCbx.getSelectedItem().toString(), kalanIzinMikTf.getText(),
                    izinBasTarihTf.getText(), izinBtsTarihtf.getText(),
                    izinTuruCbx.getSelectedItem().toString(), kullanılanIzinMikTf.getText());
            
            boolean durum = izin.izinVer(izin);
            if(durum) {
                kayitNoLbl.setText(Integer.toString(Integer.parseInt(kayitNoLbl.getText()) + 1));
                JOptionPane.showMessageDialog(null, "Ekleme Başarıyla Tamamlandı.");
            } else
                JOptionPane.showMessageDialog(null, "Ekleme Yapılamadı!");
                
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Yeni İzin Verme Hatası!\n" + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        birimTf = new javax.swing.JTextField();
        kayitNoLbl = new javax.swing.JLabel();
        sicilNoCbx = new javax.swing.JComboBox();
        kalanIzinMikTf = new javax.swing.JTextField();
        izinBasTarihTf = new javax.swing.JTextField();
        izinBtsTarihtf = new javax.swing.JTextField();
        izinTuruCbx = new javax.swing.JComboBox();
        kullanılanIzinMikTf = new javax.swing.JTextField();
        yeniIzinEkleBtn = new javax.swing.JButton();
        cikisYapBtn = new javax.swing.JButton();
        geriDonBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Yeni İzin Verme"));

        jLabel1.setText("Birim:");

        jLabel2.setText("Kayıt No:");

        jLabel3.setText("Sicil No:");

        jLabel4.setText("Kalan İzin Miktarı:");

        jLabel5.setText("İzin Başlangıç Tarihi:");

        jLabel6.setText("İzin Bitiş Tarihi:");

        jLabel7.setText("İzin Türü:");

        jLabel8.setText("Kullanılan İzin Miktarı:");

        kayitNoLbl.setText("null");

        sicilNoCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        kalanIzinMikTf.setText("0");

        izinBasTarihTf.setText("yyyy-aa-gg");

        izinBtsTarihtf.setText("yyyy-aa-gg");

        izinTuruCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yillik", "Ucretli", "Ucretsiz", "Mazeret" }));

        kullanılanIzinMikTf.setText("0");

        yeniIzinEkleBtn.setText("Yeni İzin Ekle");
        yeniIzinEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniIzinEkleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yeniIzinEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(izinBasTarihTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(birimTf)
                            .addComponent(sicilNoCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kalanIzinMikTf)
                            .addComponent(izinBtsTarihtf)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kayitNoLbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(izinTuruCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kullanılanIzinMikTf))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(birimTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kayitNoLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sicilNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kalanIzinMikTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(izinBasTarihTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(izinBtsTarihtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(izinTuruCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kullanılanIzinMikTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(yeniIzinEkleBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        cikisYapBtn.setText("Çıkış Yap");
        cikisYapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYapBtnActionPerformed(evt);
            }
        });

        geriDonBtn.setText("Geri Dön");
        geriDonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(geriDonBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikisYapBtn)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geriDonBtn)
                    .addComponent(cikisYapBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikisYapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYapBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cikisYapBtnActionPerformed

    private void geriDonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new IzinVermeMenu().setVisible(true);
    }//GEN-LAST:event_geriDonBtnActionPerformed

    private void yeniIzinEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniIzinEkleBtnActionPerformed
        // TODO add your handling code here:
        yeniIzinVer();
    }//GEN-LAST:event_yeniIzinEkleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniIzinVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniIzinVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniIzinVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniIzinVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YeniIzinVerme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birimTf;
    private javax.swing.JButton cikisYapBtn;
    private javax.swing.JButton geriDonBtn;
    private javax.swing.JTextField izinBasTarihTf;
    private javax.swing.JTextField izinBtsTarihtf;
    private javax.swing.JComboBox izinTuruCbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kalanIzinMikTf;
    private javax.swing.JLabel kayitNoLbl;
    private javax.swing.JTextField kullanılanIzinMikTf;
    private javax.swing.JComboBox sicilNoCbx;
    private javax.swing.JButton yeniIzinEkleBtn;
    // End of variables declaration//GEN-END:variables
}
