/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personelIslemleri;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import veritabani.VeritabaniBaglantisi;

public class YeniPersonelKayit extends javax.swing.JFrame {

    /**
     * Creates new form YeniPersonelKayit
     */
    public YeniPersonelKayit() {
        initComponents();
        sicilNoIcerikDuzenleme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        soyadTf = new javax.swing.JTextField();
        tcNoTf = new javax.swing.JTextField();
        cinsiyetTf = new javax.swing.JTextField();
        dogumTarihiTf = new javax.swing.JTextField();
        sehirTf = new javax.swing.JTextField();
        personelEkleBtn = new javax.swing.JButton();
        cikisBtn = new javax.swing.JButton();
        geriDonBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sicilNoLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Yeni Personel Ekleme Penceresi"));

        jLabel1.setText("Ad  :");

        jLabel2.setText("Soyad  :");

        jLabel3.setText("Tc No  :");

        jLabel4.setText("Sicil No  :");

        jLabel5.setText("Cinsiyet  :");

        jLabel6.setText("Doğum Tarihi  :");

        jLabel7.setText("Şehir  :");

        personelEkleBtn.setText("Yeni Personel Ekle");
        personelEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelEkleBtnActionPerformed(evt);
            }
        });

        cikisBtn.setText("Çıkış Yap");
        cikisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisBtnActionPerformed(evt);
            }
        });

        geriDonBtn.setText("Geri Dön");
        geriDonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Tc Numarası sayı olmak zorundadır.");

        jLabel9.setText("Doğum Tarihi bölümü \"yıl-ay-gün\" şeklinde olmalıdır.Örneğin;");

        jLabel10.setText("1994-12-27");

        sicilNoLbl.setText("null");

        jLabel11.setText("Sicil numarası son sicil no'nun bir fazlası olarak otomatik gelir.");

        jButton1.setText("Alan Temizle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(geriDonBtn)
                            .addGap(18, 18, 18)
                            .addComponent(cikisBtn))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(personelEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adTf)
                                    .addComponent(soyadTf)
                                    .addComponent(tcNoTf)
                                    .addComponent(cinsiyetTf)
                                    .addComponent(dogumTarihiTf)
                                    .addComponent(sehirTf)
                                    .addComponent(sicilNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                        .addComponent(jButton1))
                    .addComponent(jLabel11))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyadTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tcNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sicilNoLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cinsiyetTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dogumTarihiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sehirTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(personelEkleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cikisBtn)
                    .addComponent(geriDonBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriDonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonBtnActionPerformed
        this.dispose();
        new PersonelIslemleriMenu().setVisible(true);
    }//GEN-LAST:event_geriDonBtnActionPerformed

    private void cikisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisBtnActionPerformed
       dispose();
    }//GEN-LAST:event_cikisBtnActionPerformed
    
    
    VeritabaniBaglantisi vb = new VeritabaniBaglantisi();
    public Statement baglantiAc() throws Exception {
        
        Class.forName(vb.DRIVER).newInstance();
        vb.con = DriverManager.getConnection(vb.URL + vb.DB_NAME, vb.ID, vb.PW);
        return vb.con.createStatement();
    }
    public void baglantiKapat() throws SQLException {
        vb.con.close();
    }
    
    public void sicilNoIcerikDuzenleme() {
        
        try {
            Statement s = baglantiAc();
            String sql = "SELECT sicil_no FROM kisi_bilgi ORDER BY sicil_no DESC LIMIT 1";
            ResultSet rs = s.executeQuery(sql);
            
            String sicilNo = "";
            while(rs.next()) {
                sicilNo = rs.getString("sicil_no");
            }
            baglantiKapat();
            
            sicilNo = Integer.toString(Integer.parseInt(sicilNo) + 1);
            sicilNoLbl.setText(sicilNo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sicil No düzenlenirken hata oluştu!\n" + e);
        }    
            
    }
    
    private void personelEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelEkleBtnActionPerformed
        
        try {
            
            PersonelEkle p = new PersonelEkle(adTf.getText(),
                    soyadTf.getText(), tcNoTf.getText(), sicilNoLbl.getText(),
                    cinsiyetTf.getText(), dogumTarihiTf.getText(), sehirTf.getText());
            
            boolean durum = p.personelEkle(p);
            if(durum) {
                sicilNoLbl.setText(Integer.toString(Integer.parseInt(sicilNoLbl.getText()) + 1));
                JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Tamamlandı.");
            } else
                JOptionPane.showMessageDialog(null, "Kayıt Başarısız Oldu!!!");
            
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "HATA!\n" + e);
        }
    }//GEN-LAST:event_personelEkleBtnActionPerformed
    
    public void textFieldIcerikTemizleme() {
        adTf.setText("");
        soyadTf.setText("");
        tcNoTf.setText("");
        cinsiyetTf.setText("");
        dogumTarihiTf.setText("");
        sehirTf.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        textFieldIcerikTemizleme();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YeniPersonelKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTf;
    private javax.swing.JButton cikisBtn;
    private javax.swing.JTextField cinsiyetTf;
    private javax.swing.JTextField dogumTarihiTf;
    private javax.swing.JButton geriDonBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton personelEkleBtn;
    private javax.swing.JTextField sehirTf;
    private javax.swing.JLabel sicilNoLbl;
    private javax.swing.JTextField soyadTf;
    private javax.swing.JTextField tcNoTf;
    // End of variables declaration//GEN-END:variables
}
